<?php

namespace AppBundle\Repository;

/**
 * AsociacionesCajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsociacionesCajaRepository extends \Doctrine\ORM\EntityRepository
{
}
