<?php

namespace AppBundle\Repository;

/**
 * CodigoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodigoRepository extends \Doctrine\ORM\EntityRepository
{
}
