<?php

namespace AppBundle\Repository;

/**
 * FuentesCodigosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuentesCodigosRepository extends \Doctrine\ORM\EntityRepository
{
}
