<?php

namespace AppBundle\Repository;

/**
 * FuenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuenteRepository extends \Doctrine\ORM\EntityRepository
{
}
