<?php

namespace AppBundle\Repository;

/**
 * responsablesCajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class responsablesCajaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findResp($user){

		$em = $this->getEntityManager(); 
		$qb = $em->createQueryBuilder();
		$qb->select('c')
		->from('AppBundle:responsablesCaja', 'c')
		->where('c.user = :user AND c.responsable IS NOT NULL')
		->setParameter('user', $user);
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
