<?php

namespace AppBundle\Repository;

/**
 * TransaccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionRepository extends \Doctrine\ORM\EntityRepository
{
	public function lastTransaccion(){

		$em = $this->getEntityManager(); 
		$qb = $em->createQueryBuilder();
		$qb->select('t')
		   ->from('AppBundle:Transaccion', 't')
		   ->setMaxResults(10)
		   ->orderBy('t.id', 'DESC');
	  $query = $qb->getQuery();
	  return $query->getResult();
	}

	public function findUser($cajas){
		$em = $this->getEntityManager(); 
		$qb = $em->createQueryBuilder();
		$qb->select('c')
		->from('AppBundle:Transaccion', 'c')
		->where('c.cajaEnvia IN (:cajas) OR c.cajaRecibe IN (:cajas)')
		->setParameter('cajas', $cajas)
		->orderBy('c.id','DESC');
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
