<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUsers(){

		$em = $this->getEntityManager(); 
		$qb = $em->createQueryBuilder();
		$qb->select('u')
		->from('AppBundle:User', 'u')
		->where('u.username != :name')
		->setParameter('name','mike');
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
